# modules/safety_guardrails.py
"""
Safety Guardrails for Trading
Prevents bad trades, enforces risk limits, detects anomalies, and circuit breakers.
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from typing import Dict, Tuple, Optional, List
from dataclasses import dataclass


@dataclass
class TradeAlert:
    """Alert generated by guardrail checks."""
    severity: str  # INFO, WARNING, CRITICAL
    rule: str  # Rule that triggered alert
    message: str
    timestamp: datetime
    action: str  # ALLOW, WARN, BLOCK


class SafetyGuardrails:
    """
    Multi-layer safety system for trading.
    """
    
    def __init__(
        self,
        max_daily_loss_percent: float = 5.0,
        max_single_loss_percent: float = 3.0,
        max_consecutive_losses: int = 3,
        min_accuracy_threshold: float = 0.55,
        circuit_breaker_active: bool = True,
        alert_log_size: int = 100,
    ):
        """
        Initialize safety guardrails.
        
        Args:
            max_daily_loss_percent: Max loss per day (%)
            max_single_loss_percent: Max loss per single trade (%)
            max_consecutive_losses: Max consecutive losing trades
            min_accuracy_threshold: Min model accuracy required
            circuit_breaker_active: Enable trading halt on breaches
            alert_log_size: Max alerts to keep in log
        """
        self.max_daily_loss_percent = max_daily_loss_percent
        self.max_single_loss_percent = max_single_loss_percent
        self.max_consecutive_losses = max_consecutive_losses
        self.min_accuracy_threshold = min_accuracy_threshold
        self.circuit_breaker_active = circuit_breaker_active
        self.alert_log_size = alert_log_size
        
        self.alerts: List[TradeAlert] = []
        self.circuit_breaker_triggered = False
        self.circuit_breaker_timestamp = None
        self.last_trades = []  # Recent trades for streak analysis
        self.daily_loss = 0.0
        self.last_reset_date = datetime.now().date()
    
    
    def check_trade(
        self,
        ticker: str,
        entry_price: float,
        position_size: float,
        stop_loss: float,
        current_capital: float,
        confidence: float,
        model_accuracy: float,
        recent_trades: List[Dict],
    ) -> Tuple[bool, List[TradeAlert]]:
        """
        Comprehensive trade validation.
        
        Returns:
            (approved, alerts_list)
        """
        # Reset daily loss if new day
        today = datetime.now().date()
        if today != self.last_reset_date:
            self.daily_loss = 0.0
            self.last_reset_date = today
            self.circuit_breaker_triggered = False
        
        self.alerts = []
        
        # Check 1: Circuit breaker
        if self.circuit_breaker_triggered:
            alert = TradeAlert(
                severity="CRITICAL",
                rule="CIRCUIT_BREAKER_ACTIVE",
                message=f"Circuit breaker tripped since {self.circuit_breaker_timestamp}. No trading allowed.",
                timestamp=datetime.now(),
                action="BLOCK"
            )
            self.alerts.append(alert)
            return False, self.alerts
        
        # Check 2: Model accuracy threshold
        if model_accuracy < self.min_accuracy_threshold:
            alert = TradeAlert(
                severity="CRITICAL",
                rule="MODEL_ACCURACY_LOW",
                message=f"Model accuracy {model_accuracy:.1%} < {self.min_accuracy_threshold:.1%} threshold",
                timestamp=datetime.now(),
                action="BLOCK"
            )
            self.alerts.append(alert)
            return False, self.alerts
        
        # Check 3: Confidence check
        if confidence < 0.50:
            alert = TradeAlert(
                severity="WARNING",
                rule="LOW_CONFIDENCE",
                message=f"Confidence {confidence:.1%} below recommended 50%",
                timestamp=datetime.now(),
                action="WARN"
            )
            self.alerts.append(alert)
        
        # Check 4: Daily loss limit
        risk_amount = abs(entry_price - stop_loss) * position_size
        potential_daily_loss = self.daily_loss + risk_amount
        max_daily_loss = current_capital * (self.max_daily_loss_percent / 100)
        
        if potential_daily_loss > max_daily_loss:
            alert = TradeAlert(
                severity="CRITICAL",
                rule="DAILY_LOSS_LIMIT",
                message=f"Daily loss Rs {potential_daily_loss:.0f} exceeds Rs {max_daily_loss:.0f} limit",
                timestamp=datetime.now(),
                action="BLOCK"
            )
            self.alerts.append(alert)
            return False, self.alerts
        
        # Check 5: Single trade max loss
        max_single_loss = current_capital * (self.max_single_loss_percent / 100)
        if risk_amount > max_single_loss:
            alert = TradeAlert(
                severity="WARNING",
                rule="SINGLE_TRADE_RISK_HIGH",
                message=f"Trade risk Rs {risk_amount:.0f} exceeds Rs {max_single_loss:.0f} per-trade limit",
                timestamp=datetime.now(),
                action="WARN"
            )
            self.alerts.append(alert)
        
        # Check 6: Consecutive losses warning
        if recent_trades:
            # Get last N trades
            last_trades = recent_trades[-5:]
            losing_streak = sum(1 for t in last_trades if t.get("pnl", 0) < 0)
            
            if losing_streak >= self.max_consecutive_losses:
                alert = TradeAlert(
                    severity="CRITICAL",
                    rule="LOSING_STREAK",
                    message=f"{losing_streak} consecutive losses. Consider review.",
                    timestamp=datetime.now(),
                    action="BLOCK"
                )
                self.alerts.append(alert)
                self._trigger_circuit_breaker("Losing streak detected")
                return False, self.alerts
            
            elif losing_streak >= 2:
                alert = TradeAlert(
                    severity="WARNING",
                    rule="LOSING_STREAK_WARNING",
                    message=f"{losing_streak} consecutive losses. Be cautious.",
                    timestamp=datetime.now(),
                    action="WARN"
                )
                self.alerts.append(alert)
        
        # Check 7: Duplicate/correlated trades
        for prev_trade in recent_trades[-3:]:
            if prev_trade.get("ticker") == ticker:
                time_diff = (datetime.now() - pd.to_datetime(prev_trade.get("exit_time", datetime.now()))).total_seconds() / 3600
                
                if time_diff < 4:  # Traded same stock within 4 hours
                    alert = TradeAlert(
                        severity="WARNING",
                        rule="DUPLICATE_TRADE",
                        message=f"Recently traded {ticker} (4h ago). Avoid clustering.",
                        timestamp=datetime.now(),
                        action="WARN"
                    )
                    self.alerts.append(alert)
        
        # Check 8: Volatility spike
        # (Would need volatility data from price history)
        
        # All checks passed
        if not any(a.severity == "CRITICAL" for a in self.alerts):
            self._log_alert(TradeAlert(
                severity="INFO",
                rule="TRADE_APPROVED",
                message=f"Trade approved: {ticker} @ Rs {entry_price}",
                timestamp=datetime.now(),
                action="ALLOW"
            ))
            return True, self.alerts
        
        return False, self.alerts
    
    
    def _trigger_circuit_breaker(self, reason: str):
        """
        Trigger circuit breaker - halt all trading.
        """
        self.circuit_breaker_triggered = True
        self.circuit_breaker_timestamp = datetime.now()
        
        alert = TradeAlert(
            severity="CRITICAL",
            rule="CIRCUIT_BREAKER_TRIGGERED",
            message=f"Circuit breaker activated: {reason}",
            timestamp=datetime.now(),
            action="BLOCK"
        )
        self._log_alert(alert)
    
    
    def reset_circuit_breaker(self):
        """
        Manually reset circuit breaker (admin action).
        """
        self.circuit_breaker_triggered = False
        self.circuit_breaker_timestamp = None
        
        alert = TradeAlert(
            severity="INFO",
            rule="CIRCUIT_BREAKER_RESET",
            message="Circuit breaker manually reset",
            timestamp=datetime.now(),
            action="ALLOW"
        )
        self._log_alert(alert)
    
    
    def update_daily_loss(self, pnl: float):
        """
        Update daily loss tracking.
        """
        # Reset if new day
        today = datetime.now().date()
        if today != self.last_reset_date:
            self.daily_loss = 0.0
            self.last_reset_date = today
        
        self.daily_loss += pnl
    
    
    def _log_alert(self, alert: TradeAlert):
        """
        Log alert and manage alert history.
        """
        self.alerts.append(alert)
        
        # Keep only recent alerts
        if len(self.alerts) > self.alert_log_size:
            self.alerts = self.alerts[-self.alert_log_size:]
    
    
    def get_alert_summary(self) -> Dict:
        """
        Get summary of recent alerts.
        """
        if not self.alerts:
            return {"status": "OK", "alerts_count": 0}
        
        critical = sum(1 for a in self.alerts if a.severity == "CRITICAL")
        warnings = sum(1 for a in self.alerts if a.severity == "WARNING")
        
        return {
            "status": "HALTED" if self.circuit_breaker_triggered else "ACTIVE",
            "circuit_breaker_active": self.circuit_breaker_triggered,
            "total_alerts": len(self.alerts),
            "critical_alerts": critical,
            "warnings": warnings,
            "daily_loss": round(self.daily_loss, 2),
            "latest_alerts": [
                {
                    "severity": a.severity,
                    "rule": a.rule,
                    "message": a.message,
                    "timestamp": a.timestamp.isoformat(),
                }
                for a in self.alerts[-5:]  # Last 5 alerts
            ]
        }
    
    
    def get_alert_report(self) -> pd.DataFrame:
        """
        Export alerts as DataFrame for analysis.
        """
        if not self.alerts:
            return pd.DataFrame()
        
        data = []
        for alert in self.alerts:
            data.append({
                "Timestamp": alert.timestamp,
                "Severity": alert.severity,
                "Rule": alert.rule,
                "Message": alert.message,
                "Action": alert.action,
            })
        
        return pd.DataFrame(data)


class AnomalyDetector:
    """
    Detect anomalous price movements and model behavior.
    """
    
    def __init__(self, window_size: int = 20):
        """
        Initialize anomaly detector.
        
        Args:
            window_size: Number of recent prices for baseline
        """
        self.window_size = window_size
        self.price_history = {}
    
    
    def check_price_anomaly(
        self,
        ticker: str,
        current_price: float,
        threshold_std: float = 3.0  # 3 sigma
    ) -> Tuple[bool, Optional[Dict]]:
        """
        Detect unusual price movements.
        
        Returns:
            (is_anomaly, anomaly_details)
        """
        if ticker not in self.price_history:
            self.price_history[ticker] = []
        
        history = self.price_history[ticker]
        history.append(current_price)
        
        # Keep only recent prices
        if len(history) > self.window_size:
            history = history[-self.window_size:]
            self.price_history[ticker] = history
        
        if len(history) < 5:
            return False, None
        
        prices = np.array(history)
        mean_price = np.mean(prices[:-1])  # Exclude current
        std_price = np.std(prices[:-1])
        
        z_score = abs((current_price - mean_price) / std_price) if std_price > 0 else 0
        
        if z_score > threshold_std:
            return True, {
                "ticker": ticker,
                "price": current_price,
                "mean": mean_price,
                "std": std_price,
                "z_score": z_score,
                "severity": "HIGH" if z_score > 4.0 else "MEDIUM",
            }
        
        return False, None
    
    
    def check_prediction_anomaly(
        self,
        confidence_history: List[float],
        accuracy_history: List[float],
        threshold: float = 0.5
    ) -> Tuple[bool, Optional[str]]:
        """
        Detect anomalous model behavior (confidence collapse, accuracy drop).
        """
        if len(confidence_history) < 5:
            return False, None
        
        recent_conf = np.mean(confidence_history[-5:])
        older_conf = np.mean(confidence_history[-10:-5]) if len(confidence_history) >= 10 else recent_conf
        
        confidence_drop = (older_conf - recent_conf) / older_conf if older_conf > 0 else 0
        
        if confidence_drop > threshold:
            return True, f"Confidence dropped {confidence_drop:.1%} (was {older_conf:.1%}, now {recent_conf:.1%})"
        
        return False, None
